import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/layouts/header";
import Container from "@/layouts/container";
import Footer from "@/layouts/footer";

import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import ReduxProvider from "@/providers/redux-provider";
import AadProvider from "@/providers/aad-provider";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div id='modal-portal' className='w-screen h-screen fixed' />
          <AadProvider>
            <ReduxProvider>
              <Header />
              <ToastContainer />
              <Container>{children}</Container>
              <Footer />
            </ReduxProvider>
          </AadProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
